language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  run: "knex migrate:latest"
app: travis-test
skip_cleanup: true